name: Build executable binary with PyInstaller

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
          # - name: macos-latest
          # - name: ubuntu-latest
          - name: windows-latest

    runs-on: ${{ matrix.os.name }}

    env:
      VERSION_REF: ${{ github.ref_type == 'tag' && github.ref_name || github.sha }}

    steps:
      - name: Install dependencies
        run: |
          pip install --user pipx
          pipx install poetry
          poetry self add poetry-pyinstaller-plugin

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Build executable
        run: |
          poetry build
          mkdir -p haybox-windows
          cp ./dist/pyinstaller/win_amd64/haybox.exe haybox-windows/haybox-${VERSION_REF}.exe
      
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: haybox-cli-${{ env.VERSION_REF }}
          path: haybox-windows/haybox-${{ env.VERSION_REF }}.exe

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: haybox-windows/haybox-${{ env.VERSION_REF }}.exe